### ISSUE TITLE
2gisLaunch.exe

### ISSUE THREAD

**Issue by phant** [stealzy/2GISLaunch#1]
куда делся экзешник из репозитория?
![2017-01-02_12-31-51](https://cloud.githubusercontent.com/assets/805222/21585695/7fe97b84-d0e7-11e6-85d1-e2f4bda4a627.png)

**Comment by stealzy** [comment]
Какой еще экзешник?
RunAsDate на месте, как и был с самого начала.

**Comment by phant** [comment]
Экзешник, который я потерял (2gisLaunch.exe) был экзешник AutoHotkey, один из сайтов дополнил им вашу сборку.
![2017-07-12_19-15-14](https://user-images.githubusercontent.com/805222/28122039-79c69134-6736-11e7-9a9f-3223cc3fd7a7.png)

**Comment by stealzy** [comment]
Уже добавлен по просьбам.
Изначально здесь велась только разработка, а релиз загружался на файлообменник, поэтому этот момент упустил из виду.
