### ISSUE TITLE
На карте показываются рекламные иконки

### ISSUE THREAD

**Issue by rick1177** [stealzy/2GISLaunch#2]
Приветствую.
Спасибо за это ценное приложение. Хотел спросить нет ли возможности отключать с карты всякие рекламные знаки. 
![2020-03-19_18-03-24](https://user-images.githubusercontent.com/29839126/77070606-549dc900-6a0c-11ea-9a2f-ec5c3e715043.png)
Я прикрепляю пример того, что хотелось бы убрать. 
Конечно же, было бы отлично, если бы и иные мелкие круглые иконки ушли: вилка с ложкой, кувшин  и т.д.

Спасибо.

**Comment by rick1177** [comment]
Такие значки можно увидеть на карте Перми, например.

**Comment by stealzy** [comment]
Рекламные иконки организаций были введены методом добавления нового слоя в базы данных городов в ≈апреле 2018. Сама программа осталась без изменений, соответственно, встроенного способа спрятать значки не предусмотрено.

Вы можете:
- Распотрошить базу .dgdat (известно как это сделать), найти способ вырезать слой иконок, и собрать базу обратно. Если у вас получится, напишите как, я обновлю лаунчер. Это должно быть несложно, но я не занимался.
- Пользоваться старыми базами.

**Comment by rakf** [comment]
> Рекламные иконки организаций были введены методом добавления нового слоя в базы данных городов в ≈апреле 2018. Сама программа осталась без изменений, соответственно, встроенного способа спрятать значки не предусмотрено.
> 
> Вы можете:
> 
> * Распотрошить базу .dgdat (известно как это сделать), найти способ вырезать слой иконок, и собрать базу обратно. Если у вас получится, напишите как, я обновлю лаунчер. Это должно быть несложно, но я не занимался.
> * Пользоваться старыми базами.

Подскажите, пытался расковырять dgdat, но не удалось. МОжет быть вы знаете какие-либо источники? Структуру базы? Просто нигде не нашел

**Comment by stealzy** [comment]
Начать можно отсюда:
https://www.cyberforum.ru/csharp-net/thread519674.html
https://github.com/littlepoorgirlfromsyriya/1
Пишите, если что, буду на связи.
